from odoo import fields, models, api, tools
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta


class CohortAnalysisReport(models.Model):
    """
    Cohort Analysis Report for tracking customer behavior over time
    Groups customers by acquisition month and tracks their activity patterns
    """
    _name = 'wa_marketing_automation.cohort_analysis_report'
    _description = 'Cohort Analysis Report'
    _auto = False
    _rec_name = 'cohort_period'

    # Core identifiers
    partner_id = fields.Many2one('res.partner', string='Customer', readonly=True)
    cohort_period = fields.Date(string='Cohort Period', readonly=True, help='Month when customer was acquired')
    cohort_period_month = fields.Char(string='Cohort Month', readonly=True)
    period_number = fields.Integer(string='Period Number', readonly=True, help='Number of months since acquisition')
    
    # Customer metrics
    customers_acquired = fields.Integer(string='Customers Acquired', readonly=True, help='Number of customers acquired in this cohort')
    customers_active = fields.Integer(string='Active Customers', readonly=True, help='Number of active customers in this period')
    retention_rate = fields.Float(string='Retention Rate (%)', readonly=True, help='Percentage of customers still active')
    
    # Revenue metrics
    total_revenue = fields.Float(string='Total Revenue', readonly=True, help='Total revenue generated by this cohort in this period')
    average_revenue_per_customer = fields.Float(string='Avg Revenue/Customer', readonly=True, help='Average revenue per customer')
    cumulative_revenue = fields.Float(string='Cumulative Revenue', readonly=True, help='Total revenue since acquisition')
    
    # Engagement metrics
    avg_engagement_score = fields.Float(string='Avg Engagement Score', readonly=True, help='Average engagement score for this cohort')
    avg_rfm_score = fields.Float(string='Avg RFM Score', readonly=True, help='Average RFM score for this cohort')
    churn_risk_customers = fields.Integer(string='High Churn Risk Customers', readonly=True, help='Number of customers at high churn risk')
    
    # Journey stage distribution
    awareness_customers = fields.Integer(string='Awareness Stage', readonly=True)
    consideration_customers = fields.Integer(string='Consideration Stage', readonly=True)
    purchase_customers = fields.Integer(string='Purchase Stage', readonly=True)
    loyalty_customers = fields.Integer(string='Loyalty Stage', readonly=True)
    advocacy_customers = fields.Integer(string='Advocacy Stage', readonly=True)
    dormant_customers = fields.Integer(string='Dormant Stage', readonly=True)
    
    # Computed fields
    cohort_age_months = fields.Integer(string='Cohort Age (Months)', readonly=True, help='Age of cohort in months')
    customer_lifetime_value = fields.Float(string='Customer Lifetime Value', readonly=True, help='Average CLV for this cohort')
    
    def init(self):
        """Initialize the cohort analysis report view"""
        tools.drop_view_if_exists(self.env.cr, self._table)
        self.env.cr.execute("""
            CREATE OR REPLACE VIEW %s AS (
                WITH cohort_data AS (
                    -- Get customer acquisition dates (first order date)
                    SELECT 
                        rp.id as partner_id,
                        DATE_TRUNC('month', MIN(so.date_order)) as cohort_period,
                        TO_CHAR(DATE_TRUNC('month', MIN(so.date_order)), 'YYYY-MM') as cohort_period_month
                    FROM res_partner rp
                    LEFT JOIN sale_order so ON rp.id = so.partner_id AND so.state IN ('sale', 'done')
                    WHERE rp.is_company = false 
                    AND rp.active = true
                    AND rp.customer_rank > 0
                    GROUP BY rp.id
                ),
                period_data AS (
                    -- Generate periods (months) for analysis
                    SELECT 
                        cohort_period,
                        cohort_period_month,
                        generate_series(0, 23) as period_number  -- 24 months of data
                    FROM (
                        SELECT DISTINCT cohort_period, cohort_period_month 
                        FROM cohort_data 
                        WHERE cohort_period IS NOT NULL
                    ) cohorts
                ),
                customer_activity AS (
                    -- Calculate customer activity for each period
                    SELECT 
                        cd.partner_id,
                        cd.cohort_period,
                        cd.cohort_period_month,
                        pd.period_number,
                        cd.cohort_period + (pd.period_number || ' months')::interval as analysis_period,
                        
                        -- Check if customer was active in this period
                        CASE 
                            WHEN EXISTS (
                                SELECT 1 FROM sale_order so2 
                                WHERE so2.partner_id = cd.partner_id 
                                AND so2.state IN ('sale', 'done')
                                AND DATE_TRUNC('month', so2.date_order) = cd.cohort_period + (pd.period_number || ' months')::interval
                            ) THEN 1 
                            ELSE 0 
                        END as is_active,
                        
                        -- Calculate revenue for this period
                        COALESCE((
                            SELECT SUM(so3.amount_total) 
                            FROM sale_order so3 
                            WHERE so3.partner_id = cd.partner_id 
                            AND so3.state IN ('sale', 'done')
                            AND DATE_TRUNC('month', so3.date_order) = cd.cohort_period + (pd.period_number || ' months')::interval
                        ), 0) as period_revenue,
                        
                        -- Calculate cumulative revenue
                        COALESCE((
                            SELECT SUM(so4.amount_total) 
                            FROM sale_order so4 
                            WHERE so4.partner_id = cd.partner_id 
                            AND so4.state IN ('sale', 'done')
                            AND DATE_TRUNC('month', so4.date_order) <= cd.cohort_period + (pd.period_number || ' months')::interval
                        ), 0) as cumulative_revenue
                        
                    FROM cohort_data cd
                    JOIN period_data pd ON cd.cohort_period = pd.cohort_period
                    WHERE cd.cohort_period + (pd.period_number || ' months')::interval <= DATE_TRUNC('month', CURRENT_DATE)
                )
                
                SELECT 
                    ROW_NUMBER() OVER (ORDER BY cohort_period, period_number) as id,
                    NULL::integer as partner_id,  -- Individual customer data not needed for aggregated view
                    cohort_period,
                    cohort_period_month,
                    period_number,
                    
                    -- Cohort size (customers acquired)
                    (SELECT COUNT(DISTINCT partner_id) FROM cohort_data cd2 WHERE cd2.cohort_period = ca.cohort_period) as customers_acquired,
                    
                    -- Active customers in this period
                    COUNT(CASE WHEN is_active = 1 THEN 1 END) as customers_active,
                    
                    -- Retention rate
                    ROUND(
                        (COUNT(CASE WHEN is_active = 1 THEN 1 END) * 100.0 / 
                        NULLIF((SELECT COUNT(DISTINCT partner_id) FROM cohort_data cd3 WHERE cd3.cohort_period = ca.cohort_period), 0))::numeric,
                        2
                    ) as retention_rate,
                    
                    -- Revenue metrics
                    SUM(period_revenue) as total_revenue,
                    ROUND(
                        (SUM(period_revenue) / NULLIF(COUNT(CASE WHEN is_active = 1 THEN 1 END), 0))::numeric,
                        2
                    ) as average_revenue_per_customer,
                    ROUND(AVG(cumulative_revenue)::numeric, 2) as cumulative_revenue,
                    
                    -- Engagement metrics (using partner data)
                    ROUND(AVG(
                        CASE WHEN is_active = 1 THEN 
                            COALESCE((SELECT overall_engagement_score FROM res_partner WHERE id = ca.partner_id), 0)
                        END
                    )::numeric, 2) as avg_engagement_score,
                    
                    ROUND(AVG(
                        CASE WHEN is_active = 1 THEN 
                            COALESCE((SELECT rfm_score FROM res_partner WHERE id = ca.partner_id), 0)
                        END
                    )::numeric, 2) as avg_rfm_score,
                    
                    COUNT(CASE 
                        WHEN is_active = 1 AND 
                             (SELECT churn_risk_level FROM res_partner WHERE id = ca.partner_id) IN ('high', 'very_high') 
                        THEN 1 
                    END) as churn_risk_customers,
                    
                    -- Journey stage distribution
                    COUNT(CASE 
                        WHEN is_active = 1 AND 
                             (SELECT customer_journey_stage FROM res_partner WHERE id = ca.partner_id) = 'awareness' 
                        THEN 1 
                    END) as awareness_customers,
                    
                    COUNT(CASE 
                        WHEN is_active = 1 AND 
                             (SELECT customer_journey_stage FROM res_partner WHERE id = ca.partner_id) = 'consideration' 
                        THEN 1 
                    END) as consideration_customers,
                    
                    COUNT(CASE 
                        WHEN is_active = 1 AND 
                             (SELECT customer_journey_stage FROM res_partner WHERE id = ca.partner_id) = 'purchase' 
                        THEN 1 
                    END) as purchase_customers,
                    
                    COUNT(CASE 
                        WHEN is_active = 1 AND 
                             (SELECT customer_journey_stage FROM res_partner WHERE id = ca.partner_id) = 'loyalty' 
                        THEN 1 
                    END) as loyalty_customers,
                    
                    COUNT(CASE 
                        WHEN is_active = 1 AND 
                             (SELECT customer_journey_stage FROM res_partner WHERE id = ca.partner_id) = 'advocacy' 
                        THEN 1 
                    END) as advocacy_customers,
                    
                    COUNT(CASE 
                        WHEN is_active = 1 AND 
                             (SELECT customer_journey_stage FROM res_partner WHERE id = ca.partner_id) = 'dormant' 
                        THEN 1 
                    END) as dormant_customers,
                    
                    -- Cohort age
                    period_number as cohort_age_months,
                    
                    -- Customer lifetime value (cumulative revenue / cohort size)
                    ROUND(
                        (AVG(cumulative_revenue) / NULLIF(
                            (SELECT COUNT(DISTINCT partner_id) FROM cohort_data cd4 WHERE cd4.cohort_period = ca.cohort_period), 
                            0
                        ))::numeric,
                        2
                    ) as customer_lifetime_value
                    
                FROM customer_activity ca
                GROUP BY cohort_period, cohort_period_month, period_number
                ORDER BY cohort_period, period_number
            )
        """ % self._table)