{
    "name": "Smart Engagement",
    "version": "18.0.1.0.0",
    "category": "Marketing",
    "summary": "Smart Engagement - Intelligent customer analytics, automated campaigns, and AI-powered customer intelligence suite",
    "description": "Smart engagement platform featuring intelligent customer analytics, RFM analysis, behavioral insights, churn prediction, automated messaging campaigns, customer segmentation, and AI-powered business intelligence reports. Includes WhatsApp automation, multi-channel engagement tracking, and configurable customer journey management for data-driven marketing decisions.",
    "author": "Antony Gunawan",
    "depends": ["base", "mail", "crm", "contacts", "sale", "base_automation"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/default_customer_age_groups.xml",
        "data/default_customer_spending_tiers.xml",
        "data/default_customer_acquisition_sources.xml",
        "data/sample_customers.xml",
        "data/force_analytics_computation.xml",
        "data/server_actions.xml",
        "data/webhook_server_actions.xml",
        "data/webhook_automation_rules.xml",
        "views/campaign_views.xml",
        "views/customer_segmentation_views.xml",
        "views/whatsapp_api_log_views.xml",
        "views/scheduled_actions_views.xml",
        "views/res_partner_views.xml",
        "views/customer_spending_tier_config_views.xml",
        "views/customer_age_group_config_views.xml",
        "views/customer_acquisition_source_config_views.xml",
        "views/res_config_settings_views.xml",
        "views/config_action_views.xml",
        "views/reports/performance_analytics_report_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3",
}
