{
    "name": "WhatsApp Marketing Automation",
    "version": "18.0.1.0.0",
    "category": "Marketing",
    "summary": "WhatsApp Marketing Automation - Streamline campaigns, engage customers, and boost conversions with automated messaging workflows",
    "description": "Comprehensive WhatsApp marketing automation platform for creating, managing, and optimizing customer engagement campaigns. Features include automated messaging workflows, campaign scheduling, audience segmentation, performance analytics, and integration with WhatsApp Business API for seamless communication and lead generation.",
    "author": "Antony Gunawan",
    "depends": ["base", "mail", "crm"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "views/campaign_views.xml",
        "views/customer_segmentation_views.xml",
        "views/configuration_views.xml",
        "views/whatsapp_api_log_views.xml",
        "views/scheduled_actions_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3",
}
